[project]
name = 'ForestChain-Guardian'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.deforestation-detection-system]
path = 'contracts/deforestation-detection-system.clar'
clarity_version = 3
epoch = '3.2'

[contracts.forest-biodiversity-registry]
path = 'contracts/forest-biodiversity-registry.clar'
clarity_version = 3
epoch = '3.2'

[contracts.forest-stewardship-rewards]
path = 'contracts/forest-stewardship-rewards.clar'
clarity_version = 3
epoch = 'latest'

[contracts.sustainable-logging-verification]
path = 'contracts/sustainable-logging-verification.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
